### ISSUE TITLE
Build & Test Failed for Python2.7

### ISSUE THREAD

**Issue by koladiya** [StackStorm-Exchange/stackstorm-cisco_aci#11]
Hi,
I did Pull Request, however it is failing for Python2.7 having too long line. could you please have a look on it? 

This is my small code snippet.

> line 51

` ingress_data_plane_policing_policy['infraRsQosIngressDppIfPol']['attributes']['tnQosDppPolName'] = Ingress_Data_Plane_Policing_Policy`

**Error from Pull Request (Run Tests Python2.7 )**
> . ~/virtualenv/bin/activate; if [ ! "actions/create_interface_leaf_policy_group.py actions/create_snapshot.py actions/create_tenant.py actions/get_snapshots.py actions/lib/aci.py" ]; then echo "No files have changed, skipping run..."; fi; for file in actions/create_interface_leaf_policy_group.py actions/create_snapshot.py actions/create_tenant.py actions/get_snapshots.py actions/lib/aci.py; do if [ -n "$file" ]; then flake8 --config=/home/circleci/ci/lint-configs/python/.flake8 $file || exit 1; fi; done
> actions/create_interface_leaf_policy_group.py:44:101: E501 line too long (102 > 100 characters)
> actions/create_interface_leaf_policy_group.py:51:101: E501 line too long (141 > 100 characters)
> actions/create_interface_leaf_policy_group.py:58:101: E501 line too long (134 > 100 characters)
> actions/create_interface_leaf_policy_group.py:65:101: E501 line too long (138 > 100 characters)
> actions/create_interface_leaf_policy_group.py:79:101: E501 line too long (104 > 100 characters)
> actions/create_interface_leaf_policy_group.py:121:101: E501 line too long (120 > 100 characters)
> actions/create_interface_leaf_policy_group.py:128:101: E501 line too long (124 > 100 characters)
> actions/create_interface_leaf_policy_group.py:142:101: E501 line too long (113 > 100 characters)
> actions/create_interface_leaf_policy_group.py:149:101: E501 line too long (128 > 100 characters)
> Makefile:65: recipe for target '.flake8' failed
> make: *** [.flake8] Error 1
> Exited with code 2

**Comment by LindsayHill** [comment]
Looks like you have the same problem in a lot of places. You need to break your lines so they are less than 100 characters. 

Depending on the code, there are different ways of doing this. Look at https://github.com/StackStorm-Exchange/stackstorm-cisco_aci/blob/master/actions/lib/aci.py#L74 or https://github.com/StackStorm-Exchange/stackstorm-cisco_aci/blob/master/actions/lib/aci.py#L145 as examples

**Comment by koladiya** [comment]
@LindsayHill thanks for the suggestion. You can close this issue.

**Comment by koladiya** [comment]
solved
